# Generated by Django 4.2.2 on 2023-06-20 12:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
