# Generated by Django 4.2.2 on 2023-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_skill_color_alter_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=200)),
            ],
        ),
    ]
