# Generated by Django 4.2.2 on 2023-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brnad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='brands/')),
            ],
        ),
    ]
