# Generated by Django 4.2.2 on 2023-07-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_brnad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brnad',
            new_name='Brand',
        ),
    ]
