# Generated by Django 4.2.2 on 2023-07-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_reply_reply_alter_reply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='blog',
        ),
    ]
